name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: 
      - main
      - jenk
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
       ref: main
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Show Node version
      run: 'node -v'

    - name: List files
      run: 'ls -al'

    - name: Install Dependencies
      run: 'npm install'

    - name: Test application
      run: 'npm test'

    - name: Run tests
      run: echo "Tests to be added"
